config/routes.rb
Rails.application.routes.draw do
  root :to => 'products#index'

  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews

  validates :name, :presence => true
  validates :cost, :presence => true
  validates :cost, numericality: { only_integer: true }
  validates :cost, inclusion: { in: 1..20, message: "must be less than or equal to 20" }
  validates :origin, :presence => true

  scope :three_most_recent, -> { order(created_at: :desc).limit(3) }
  scope :made_in_the_usa, -> { where(origin: "United States of America")}

  scope :most_reviews, -> {(select("products.id, products.name, products.cost, products.origin, count(reviews.id) as reviews_count").joins(:reviews).group("products.id").order("reviews_count DESC").limit(10))}
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product

  validates :author, :presence => true
  validates :content, :presence => true
  validates :content, length: { minimum: 50, maximum: 250 }
  validates :rating, :presence => true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: { in: 1..5, message: "must be less than or equal to 5" }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all.limit(10)
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Thanks for adding to our menu!"
      redirect_to  products_path
    else
      render :new
    end
  end

  def edit
     @product = Product.find(params[:id])
   end

  def update
    @product= Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      flash[:alert] = "You have deleted the product #{@product.name}!"
      redirect_to products_path
    end
  end

private
  def product_params
    params.require(:product).permit(:name, :cost, :origin)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Thanks for creating a review!"
      redirect_to product_path(@review.product)
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
  end

  def update
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to product_path(@review.product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    if @review.destroy
      flash[:alert] = "You have deleted #{@review.author}'s review!"
      redirect_to product_path(@review.product)
    end
  end


private
  def review_params
    params.require(:review).permit(:author, :content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MariosSpecialityFoodProducts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

      <%= flash[:alert] %>
      <%= flash[:notice] %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :cost %>
  <%= f.number_field(:cost, in: 1..20) %>
  <%= f.label :origin %>
  <%= f.text_field :origin %>
  <%= f.submit  %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit product</h1>

<%= render "form" %>

<p><%= link_to "Return to Home", products_path %></p>

app/views/products/index.html.erb
<h1>Products</h1>


<% if @products.any? %>
  <h4>Here are the three most recent products:</h4>

  <ul class="list-unstyled">
    <% @products.three_most_recent.each do |product| %>
      <li><%= link_to product.name, product_path(product) %> $<%= product.cost %>.00 <%= product.origin %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no reviews yet!</p>
<% end %>

<% if @products.any? %>
  <h4>Here are products made in the USA:</h4>

  <ul class="list-unstyled">
    <% @products.made_in_the_usa.each do |product| %>
      <li><%= link_to product.name, product_path(product) %> $<%= product.cost %>.00 <%= product.origin %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no reviews yet!</p>
<% end %>


<% if @products.any? %>
  <h4>Here are 10 of our products:</h4>

  <ul class="list-unstyled">
    <% @products.each do |product| %>
      <li><%= link_to product.name, product_path(product) %> $<%= product.cost %>.00 <%= product.origin %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no reviews yet!</p>
<% end %>

<% if @products.any? %>
  <h4>Here the products with the most reviews:</h4>

  <ul class="list-unstyled">
    <% @products.most_reviews.each do |product| %>
      <li><%= link_to product.name, product_path(product) %> $<%= product.cost %>.00 <%= product.origin %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no reviews yet!</p>
<% end %>

<%= link_to "Create", new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form" %>

<p><%= link_to "Return to Home", products_path %></p>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<% if @product.reviews.any? %>
  <h4>Here are the reviews for this product:</h4>

  <ul class="list-unstyled">
    <% @product.reviews.each do |review| %>
      <li>
        <%= review.author %> <%= review.rating %> <%= review.content %> |
        <%= link_to "Edit", edit_product_review_path(@product, review) %> |
        <%= link_to "Delete", product_review_path(@product, review),
                                 :data => {:confirm => "Are you sure?",
                                                :method => "delete"} %>

      </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no reviews yet!</p>
<% end %>

<p><%= link_to "Add Review", new_product_review_path(@product) %></p>
<p><%= link_to "Edit Product", edit_product_path(@product) %></p>
<p><%= link_to "Delete Product", product_path(@product),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>

<p><%= link_to "Return to Home", products_path %></p>

app/views/reviews/_form.html.erb
<%= render('layouts/errors', :object => @review) %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.label :rating %>
  <%= f.number_field(:rating, in: 1..5) %>
  <%= f.submit %>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit review for <%= @product.name %></h1>

<%= render 'form' %>

app/views/reviews/new.html.erb
<h1>New review for <%= @product.name %></h1>

<%= render 'form' %>